#!/usr/bin/env bash

# You can execute me through Glide by doing the following:
# - Execute `glide slow`
# - ???
# - Profit

pushd $GOPATH/src/github.com/nightfury1204/prometheus-remote-metric-writer

glide up -v
glide vc --use-lock-file --only-code --no-tests

popd
